CREATE DATABASE DATASET;
USE DATASET;
CREATE TABLE REGION (
    R_REGIONKEY    INT,
    R_NAME         VARCHAR(25),
    R_COMMENT      VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);
-- 基础信息测试
DESC REGION;
-- 载入测试：成功
LOAD FROM FILE '../data-with-date/region.csv' TO TABLE REGION;
SELECT * FROM REGION;
-- 载入重复信息测试：失败
LOAD FROM FILE '../data-with-date/region_pk_test.csv' TO TABLE REGION;
SELECT * FROM REGION;
-- 错误update：失败
UPDATE REGION SET R_REGIONKEY = 1 WHERE REGION.R_REGIONKEY = 2;
SELECT * FROM REGION;
--正确update：成功
UPDATE REGION SET R_REGIONKEY = 6 WHERE REGION.R_REGIONKEY = 2;
SELECT * FROM REGION;
UPDATE REGION SET R_REGIONKEY = 2 WHERE REGION.R_REGIONKEY = 6;
-- 删除主键，再次插入重复信息：成功
ALTER TABLE REGION DROP PRIMARY KEY (R_REGIONKEY);
LOAD FROM FILE '../data-with-date/region_pk_test.csv' TO TABLE REGION;
SELECT * FROM REGION;
--增添主键：失败
ALTER TABLE REGION ADD PRIMARY KEY (R_REGIONKEY);
--删除重复信息后，再增添主键，再插入重复信息：失败
DELETE FROM REGION WHERE REGION.R_REGIONKEY = 1;
SELECT * FROM REGION;
ALTER TABLE REGION ADD PRIMARY KEY (R_REGIONKEY);
LOAD FROM FILE '../data-with-date/region_pk_test.csv' TO TABLE REGION;
SELECT * FROM REGION;

