CREATE DATABASE DATASET;
USE DATASET;

CREATE TABLE REGION (
    R_REGIONKEY    INT,
    R_NAME         VARCHAR(25),
    R_COMMENT      VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);
CREATE TABLE NATION (
    N_NATIONKEY      INT,
    N_NAME           VARCHAR(25),
    N_REGIONKEY      INT NOT NULL,
    N_COMMENT        VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY)
);
-- DESC REGION;
LOAD FROM FILE '../data-with-date/region.csv' TO TABLE REGION;
LOAD FROM FILE '../data-with-date/nation.csv' TO TABLE NATION;

ALTER TABLE NATION ADD FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY);
-- DESC SHADOW NATION;
-- DESC SHADOW REGION;
-- SELECT * FROM REGION WHERE REGION.R_REGIONKEY = 1;
DELETE FROM REGION WHERE REGION.R_REGIONKEY = 1;
ALTER TABLE NATION DROP FOREIGN KEY N_REGIONKEY;
-- DESC SHADOW NATION;
-- DESC SHADOW REGION;
DELETE FROM REGION WHERE REGION.R_REGIONKEY = 1;

-- UPDATE REGION SET R_REGIONKEY = 10 WHERE REGION.R_REGIONKEY = 1;
-- SELECT * FROM REGION;
