CREATE DATABASE DATASET;
USE DATASET;

CREATE TABLE REGION (
    R_REGIONKEY    INT,
    R_NAME         VARCHAR(25),
    R_COMMENT      VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);
CREATE TABLE NATION (
    N_NATIONKEY      INT,
    N_NAME           VARCHAR(25),
    N_REGIONKEY      INT NOT NULL,
    N_COMMENT        VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY)
);

LOAD FROM FILE '../data-with-date/region.csv' TO TABLE REGION;
LOAD FROM FILE '../data-with-date/nation.csv' TO TABLE NATION;

ALTER TABLE NATION ADD FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY);
LOAD FROM FILE '../data-with-date/nation_test.csv' TO TABLE NATION;
ALTER TABLE NATION DROP FOREIGN KEY N_REGIONKEY;
LOAD FROM FILE '../data-with-date/nation_test.csv' TO TABLE NATION;



-- SELECT * FROM PARTSUPP WHERE PARTSUPP.PS_SUPPKEY > 1100 AND PARTSUPP.PS_SUPPKEY < 1120;
